version: '3.1'

services:
  db:
      build: './db'
      restart: always
      environment:
        POSTGRES_PASSWORD: 'password'
      ports:
        - 5432:5432
  server:
      build: './server'
      volumes:
        - ./server:/go/src/app
      ports:
        - 8080:8080
      depends_on:
        - db
      links:
        - db
      environment:
        - DB_PATH=db
        - DB_USER=postgres
        - DB_PASSWORD=password
        - DB_NAME=postgres
  client:
      build: './client'
      ports:
        - 80:80
      environment:
        - SERVER_PATH=server
  client-dev:
      build:
        context: ./client
        dockerfile: Dockerfile.dev
      volumes:
        - ./client/node_modules:/app/node_modules
        - ./client/src/app:/app/src/app
      ports:
        - 4200:4200
      environment:
        - SERVER_PATH=server
      
